### ISSUE TITLE
Predict error

### ISSUE THREAD

**Issue by Zrufy** [hanzy88/tensorflow2ncnn#4]
hello I want to thank you for this converter and for the work you do. I wanted to ask you some information about the predict of the network converted from tensorflow to ncnn. I have a mobilenetV2 and using your build.The conversion is all right but the predict is wrong many times compared to the unconverted mobilnetV2. Do you have any help to give me?

**Comment by hanzy88** [comment]
> hello I want to thank you for this converter and for the work you do. I wanted to ask you some information about the predict of the network converted from tensorflow to ncnn. I have a mobilenetV2 and using your build.The conversion is all right but the predict is wrong many times compared to the unconverted mobilnetV2. Do you have any help to give me?

Sorry, since I have not seen your model defined I maynot give you a good answer. But you can check your preprocess for your input, like do you preprocess in the .py file but may not implement in ncnn. Also you can check the output of the layer before the last one whether they can output correctly, then maybe you can find which layer caused the problem.

**Comment by Zrufy** [comment]
it was a problem of normalization of the image. Problem solved!
